'\" -*- coding: UTF-8 -*-
.TH uninst 1
.SH NAME
uninst \- extract files from IRIX's inst packages
.SH SYNOPSIS
.nf
\fBuninst\fR [\fIOPTION\fR] \fIFILE\fR
.SH DESCRIPTION
.I uninst
extracts files from an IRIX 'inst'-style package.
.P
inst packages consist of a number of files: the \fIproduct description file\fR with no extension, the \fIidb file\fR with the .idb extension, and at least one \fIimage file\fR with various extensions. Any of these may be given to \fBuninst\fR, as long as all of them are present and named correctly.
.SH OPTIONS
.TP
.B \-h
Print a usage message on standard output and exit.
.TP
.B \-l
List files without extracting.
.TP
.B \-t
Test checksum of files in package.
.TP
.B \-v
List files while extracting.
.TP
.B \-V
Print version information on standard output and exit successfully.
.SH AUTHOR
Jason Benaim <jrra@jrra.zone>
.SH COPYRIGHT
Copyright \(co 2025 Jason Benaim, except for gun.c which is copyright \(co 2003, 2005, 2008, 2010, 2012 Mark Adler.
.br
Licensed under the GNU GPL version 2 or later, except for gun.c which is under the zlib license.
.br
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR tar (1),
.BR unzip (1)
